#!/bin/bash
echo "=== Factory Health Check ==="
source ~/.factory-env 2>/dev/null
echo ""
echo "API Keys:"
[ -n "$GOOGLE_API_KEY" ] && echo "  ✅ GOOGLE_API_KEY" || echo "  ❌ GOOGLE_API_KEY"
[ -n "$OPENROUTER_API_KEY" ] && echo "  ✅ OPENROUTER_API_KEY" || echo "  ❌ OPENROUTER_API_KEY"
[ -n "$PERPLEXITY_API_KEY" ] && echo "  ✅ PERPLEXITY_API_KEY" || echo "  ❌ PERPLEXITY_API_KEY"
[ -n "$GITHUB_TOKEN" ] && echo "  ✅ GITHUB_TOKEN" || echo "  ❌ GITHUB_TOKEN"
echo ""
echo "Tools:"
claude --version 2>/dev/null | head -1 && echo "  ✅ Claude Code" || echo "  ❌ Claude Code"
gemini --version 2>/dev/null | head -1 && echo "  ✅ Gemini CLI" || echo "  ❌ Gemini CLI"
which uvx &>/dev/null && echo "  ✅ uvx" || echo "  ❌ uvx"
echo ""
echo "GitHub:"
ssh -T git@github.com 2>&1 | head -1
echo ""
echo "Active Factory Runs:"
tmux ls 2>/dev/null || echo "  None"
echo ""
echo "Projects:"
ls ~/projects/ 2>/dev/null || echo "  None"
echo ""
echo "Disk: $(df -h / | tail -1 | awk '{print $4 " free of " $2}')"
